### ISSUE TITLE
Add support for Rouge

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-highlighters#12]
https://github.com/jneen/rouge

This is what GitHub **Pages** uses now so we should probably add support for it.

**Comment by quintesse** [comment]
We should take a look at https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/java.rb and https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/scala.rb to use as the basis for Ceylon support

**Comment by quintesse** [comment]
Luckily the structure seems very similar to that of Pygments so we could probably/hopefully just convert our [existing Ceylon lexer for Pygments](https://bitbucket.org/birkenfeld/pygments-main/src/655dbebddc23943b8047b3c139c51c22ef18fd91/pygments/lexers/jvm.py?at=default&fileviewer=file-view-default#jvm.py-911)

**Comment by bjansen** [comment]
https://github.com/jneen/rouge/pull/414

**Comment by quintesse** [comment]
Let's wait with closing until they actually merge the PR, otherwise we might forget that this is still not really done

**Comment by bjansen** [comment]
The PR was merged a long time ago :)
