### ISSUE TITLE
TextMate highlighter issues with string literals, nested comments, and more

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-highlighters#15]
- [x] Fix the issues
- [x] Submit PR to https://github.com/jeancharles-roger/ceylon-sublimetext
- [x] Get online services to update?

Example 1: Can't escape `"`

```ceylon
value x = "apples\" and oranges";
value x = "apples\" and oranges";
```

Example 2: Can't escape `'`

```ceylon
value c = '\'';
value c = '\'';
```

Example 3: String templates are unrecognized:
```ceylon
value y = "apples `` "a" + "n" + "d" `` oranges";
value y = "apples `` "a" + "n" + "d" `` oranges";
```

Example 4: Nested comments:
```ceylon
/* comment outside /* another comment */ exampleCode(1+1) */
```

Example 5: Module descriptors highlighted by the main `tmLangauge` file don't always highlight imports following the first:
```ceylon
module simple "1.0.0" {
    import ceylon.collection "1.3.2";
    import ceylon.whole "1.3.2";
}
```

**Comment by jvasileff** [comment]
See https://github.com/jeancharles-roger/ceylon-sublimetext/pull/9

Un-assigning myself so whoever knows how to interact with GitHub and others can pick this up.

**Comment by bjansen** [comment]
GitHub is simply using a git submodule that points to Jean-Charles' repo (see https://github.com/github/linguist/tree/master/vendor/grammars), so I believe once we fix the problem we should open a PR to ask GitHub to point to the new commit instead.

**Comment by bjansen** [comment]
Oh, actually we wouldn't even have to contact GitHub:

> Grammars are updated every time we build the Linguist gem and so upstream bug fixes are automatically incorporated as they are fixed.

**Comment by jvasileff** [comment]
Cool, thanks for the info @bjansen. The PR has been merged, so I'll close this and let our robot masters take over.
